services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: portfolio-3d-server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
